spring:
  application:
    name: consumer
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8766/eureka/
feign:
  hystrix:
    enabled: true
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
