server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8766/eureka/
    fetch-registry: false
    register-with-eureka: false
spring:
  security:
    user:
      name: root
      password: 123456
      roles:
